
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend